# Generated by Django 4.2.30 on 2026-06-21 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('management', '0010_parkingspot_decorationapplication_decorationreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='handler',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_packages', to=settings.AUTH_USER_MODEL, verbose_name='经办人'),
        ),
        migrations.AlterField(
            model_name='package',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL, verbose_name='收件业主'),
        ),
        migrations.AlterField(
            model_name='package',
            name='register_staff',
            field=models.ForeignKey(limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_packages', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to=settings.AUTH_USER_MODEL, verbose_name='拜访业主'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='register_staff',
            field=models.ForeignKey(limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visitors', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
    ]
